stages:
  - build
  - test
  - deploy

variables:
  DOCKER_IMAGE_TAG: "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $DOCKER_IMAGE_TAG .
    - docker push $DOCKER_IMAGE_TAG

test:
  stage: test
  script:
    - echo "Run your unit tests here"

deploy:
  stage: deploy
  script:
    - echo "Deploy your application here"
  environment:
    name: production
  only:
    - master
